name: iframe_mobile
description: A new Flutter package project.
version: 0.0.1
author: Deivão
homepage: http://flutterando.com.br/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  webview_flutter: ^0.3.17
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: