name: youtubeplayer
description: A new Flutter package project.
version: 0.1.0
author: Deivão
homepage: http://flutterando.com.br/
 
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  webview_flutter: ^0.3.17

  iframe_web: 
    path: ../platforms/iframe_web

  iframe_mobile: 
    path: ../platforms/iframe_mobile

  # iframe_web:
  #   git:
  #     url: git://github.com/davidsdearaujo/youtubeplayer.git
  #     path: platforms/iframe_web
  
  # iframe_mobile:
  #   git:
  #     url: git://github.com/davidsdearaujo/youtubeplayer.git
  #     path: platforms/iframe_mobile
    
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: